//fibonacci problem

//Question
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


function fibonacci(){

var firstNumber = 0;

var secondNumber = 1;

var currentSum = 0;

var evenSum = 0;

var evenNumber = 0;


for (i = 0; i < 1000000000; i++){

	currentSum = firstNumber + secondNumber;

	firstNumber = secondNumber;
	secondNumber = currentSum;

	console.log('Current Sum:'+ currentSum);




	if(currentSum%2 == 0){	
	
	    evenSum +=  currentSum;

	    
	    //console.log('hello');

	}

	if(currentSum > 4000000){

		break;


	}

	 


}

console.log('Even Sum:' + evenSum);
console.log('done');




}

fibonacci();
